### ISSUE TITLE
Choice of theme of icons

### ISSUE THREAD

**Issue by arsonoff** [bbidulock/xde-menu#3]
Commands:
```
xde-menugen -w icewm -0
xde-menugen -w icewm -t gnome -0
xde-menugen -w icewm -t oxygen -0
```
create absolutely identical files of the menu. Only icons from the themes Adwaita and hicolor are used.

Though icons in `/usr/share/icons/{oxygen,gnome}` available. At generation of the menu with use `icewm-xdg-menu` these icons are used.

At the same time despite existence of icons `/usr/share/icons/hicolor/16x16/apps/libreoffice6.0-*` the xde-menugen does not use them (menu items of libreoffice have no icons).
Suspicion -- it the only files in the name of which is the additional point.

How to force the xde-menugen to use icons of the necessary theme?
What priority of use of icons (for example: Adwaita> hicolor> custom_theme)?

**Comment by bbidulock** [comment]
Looking at the code, the -t option sets the theme, not the icon theme, and it doesn't really set that either.  The theme and icon theme are picked up from ~/.gtkrc-2.0.xde and, if that does not exist, ~/.gtkrc-2.0  The gtk-icon-theme-name set there is used.  So you can try setting gtk-icon-theme-name="oxygen" in ~/.gtkrc-2.0 before running it.  I will fix the program to actually set what is specified by the options, because it shouldn't go by .gtkrc-2.0 when simply generating an external menu except, perhaps to obtain a default value.

**Comment by bbidulock** [comment]
For the libreoffice icons, you need to rebuild the gtk icon cache with gtk-update-icon-cache command when you move things around in the icon directories or they will not appear to the program.  That might be what is happening there.  Otherwise, look in the corresponding libreoffice .desktop files and see what is specified for an icon there.

**Comment by bbidulock** [comment]
One other note on the icons theme, if you are running an xsettings daemon (such as xsettingsd), the setting of gtk-icon-theme-name will be used from there.  Also, if you run xde desktop tools, it will be picked up from the _XDE_ICON_THEME_NAME property on the root window.  So, you could actually set _XDE_ICON_THEME_NAME to oxygen with xprop and achieve the same effect as using gtk-icon-theme-name.

**Comment by arsonoff** [comment]
```
$ ls /usr/share/icons/hicolor/*/apps/libreoffice6.0-math*
/usr/share/icons/hicolor/128x128/apps/libreoffice6.0-math.png  /usr/share/icons/hicolor/32x32/apps/libreoffice6.0-math.png
/usr/share/icons/hicolor/16x16/apps/libreoffice6.0-math.png    /usr/share/icons/hicolor/48x48/apps/libreoffice6.0-math.png
/usr/share/icons/hicolor/256x256/apps/libreoffice6.0-math.png  /usr/share/icons/hicolor/scalable/apps/libreoffice6.0-math.svg

$ cat ~/.local/share/applications/libreoffice6.0-math.desktop 
...
Icon=libreoffice6.0-math
...
```
```
# gtk-update-icon-cache /usr/share/icons/hicolor/
# gtk-update-icon-cache /usr/share/icons/Adwaita/
``` 
Nothing

Delete the point:
```
$ cp /usr/share/icons/hicolor/16x16/apps/libreoffice6.0-math.png ~/.local/share/icons/libreoffice60-math.png
$ sed -i 's/Icon=libreoffice6.0-math/Icon=libreoffice60-math/' ~/.local/share/applications/libreoffice6.0-math.desktop
```
The icon appeared.
Simple copying of the icon in the directory will not correct.

**Comment by bbidulock** [comment]
The commits above address the '.' part.  I was treating everything after a '.' as a file extension.  Now it only recognises proper extensions.  It is amazing how many .desktop files put Icon=/usr/share/pixmaps/stupidicon.xpm  The other part was not setting an icon theme specified on the command line.  Now

    xde-menu -G -w icewm -0 -t gnome

and such yields a theme under the proper icons.
