### ISSUE TITLE
GMENU_TREE_FLAGS_INCLUDE_UNALLOCATED

### ISSUE THREAD

**Issue by bedna-KU** [bbidulock/xde-menu#8]
I tried to compile xde-menu:

```
xde-menu.c:602:24: error: ‘GMENU_TREE_FLAGS_INCLUDE_UNALLOCATED’ undeclared (first use in this function); did you mean ‘GMENU_TREE_FLAGS_INCLUDE_EXCLUDED’?
  602 |   options.treeflags |= GMENU_TREE_FLAGS_INCLUDE_UNALLOCATED;
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by bbidulock** [comment]
As stated elsewhere, this issue is due to older compatibility with libgnome-menu.  Current compatibility is with libgnome-menu-3.0 only.  Commit 1d0fe968b36154529885449f4021e1f0061fbc83 changes the build process to no longer build against libgnome-menu and require libgnome-menu-3.0 to build.  So, I think that commit fixes this issue.

**Comment by bedna-KU** [comment]
Compilation work properly.
